### PR TITLE
Set SO_REUSEADDR flag for the server socket

### PR DESCRIPTION
**Pull request by DOBRO**
PR resolves the issue regarding the error message: 
`tcp_bind: Address already in use at .../Perl/LanguageServer.pm line 418.`

There are a lot of formatting, so the main changes are in this block:
https://github.com/DOBRO/Perl-LanguageServer/commit/2d81be645f88fcf20d65a8c38e4cfbdf2f891d0b?branch=2d81be645f88fcf20d65a8c38e4cfbdf2f891d0b&diff=unified#diff-58026e237d19c9a3c4b8d488df11821f10e93a2b5e581e9d52a5cb4548f4e533R427-R431

### CODE REVIEW

**Comment by dliakh** [comment]
So we'd have more than one server trying to listening the same port?

**Comment by DOBRO** [comment]
The server should be able to serve multiple connections concurrently. Unfortunately, it's not so far.
For example, if we open two windows (workspaces) in VSCode that use `Perl::LanguageServer`, the server crashes and can't start after that. See full log attached
[LanguageServer-error.log](https://github.com/richterger/Perl-LanguageServer/files/8090229/LanguageServer-error.log)

**Comment by DOBRO** [comment]
Forgot to mention, I use VSCode + Perl extension https://marketplace.visualstudio.com/items?itemName=richterger.perl

**Comment by richterger** [comment]
Running multiple LanguageServers is solved in 2.4.0

**Pull request closed without merging**
